# 基础配置
APP_PROT: 3080

DATABASE:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: '12345678'
  # 数据库名
  database: 'nest-simple'
  # 数据库打印日志
  logging: false
  # 是否开启同步数据表功能 , 生产环境一定要关闭，开启会删除所有数据
  synchronize: true
  # 是否自动加载实体
  autoLoadEntities: true
